# Generated by Django 6.0.3 on 2026-04-02 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
    ]
