# Generated by Django 6.0.3 on 2026-04-02 18:23

from django.db import migrations, models


def backfill_primary_admins(apps, schema_editor):
    User = apps.get_model('users', 'CustomUser')
    for u in User.objects.filter(user_type='admin').iterator():
        u.is_primary_admin = True
        u.save(update_fields=['is_primary_admin'])
    for u in User.objects.filter(is_superuser=True).exclude(is_primary_admin=True).iterator():
        u.is_primary_admin = True
        u.save(update_fields=['is_primary_admin'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_primary_admin',
            field=models.BooleanField(default=False, help_text='المدير الأساسي فقط يدير حسابات المدراء الآخرين من لوحة الإدارة. المدير الفرعي يراجع الإعلانات والاشتراكات فقط.', verbose_name='مدير أساسي'),
        ),
        migrations.RunPython(backfill_primary_admins, migrations.RunPython.noop),
    ]
