# Generated by Django 6.0 on 2026-04-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_app_open_stat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appopenstat',
            options={'verbose_name': 'إحصاء فتح التطبيق', 'verbose_name_plural': 'إحصاءات فتح التطبيق'},
        ),
        migrations.AlterField(
            model_name='appopenstat',
            name='date',
            field=models.DateField(db_index=True, unique=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='appopenstat',
            name='open_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الفتحات'),
        ),
    ]
