# Generated by Django 6.0 on 2026-04-09 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_siteannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ad_request', 'طلب إعلان ممول'), ('subscription_renewal', 'طلب تجديد اشتراك'), ('community_point', 'طلب خدمة مجتمعية')], db_index=True, max_length=40, verbose_name='نوع الحدث')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('body', models.TextField(blank=True, default='', verbose_name='وصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('related_app', models.CharField(blank=True, default='', max_length=32, verbose_name='التطبيق')),
                ('related_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='المعرّف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notification_events_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'إشعار إداري',
                'verbose_name_plural': 'إشعارات إدارية',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
