# Generated by Django 6.0.4 on 2026-04-13 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_adminnotificationevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=600, unique=True, verbose_name='endpoint')),
                ('p256dh', models.CharField(max_length=256, verbose_name='p256dh')),
                ('auth', models.CharField(max_length=256, verbose_name='auth')),
                ('user_agent', models.CharField(blank=True, default='', max_length=240, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='المدير')),
            ],
            options={
                'verbose_name': 'اشتراك Push (أدمن)',
                'verbose_name_plural': 'اشتراكات Push (أدمن)',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
