"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# تحميل backend/.env للتطوير المحلي فقط.
# ملاحظة: داخل Docker Compose نريد أن تبقى متغيرات الـ environment (مثل DATABASE_URL)
# هي المسيطرة، لذلك لا نستخدم override=True هنا.
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / '.env', override=False)
except ImportError:
    pass

import dj_database_url


def _env_bool(name: str, default: bool = True) -> bool:
    """قيمة فارغة أو غير معرّفة = الافتراضي (يتفادى DEBUG='' → False)."""
    v = os.environ.get(name)
    if v is None:
        return default
    s = str(v).strip()
    if s == '':
        return default
    return s.lower() in ('1', 'true', 'yes', 'on')


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-7ulo5xvt3*-qiu3&_4@-u2#4avvx6n0yyv+ry4lbsf^)s31lcr',
)

DEBUG = _env_bool('DEBUG', True)

# محلي: localhost و127 وIPv6 (::1) وtestserver — يتفادى DisallowedHost مع البروكسي وVite على ويندوز
# إنتاج: عرّف ALLOWED_HOSTS في لوحة Render (مثل: اسم-الخدمة.onrender.com)
# _default_allowed = 'localhost,127.0.0.1,::1,testserver'
# _allowed_raw = os.environ.get('ALLOWED_HOSTS')
# if _allowed_raw is None or not str(_allowed_raw).strip():
#     _allowed_source = _default_allowed
# else:
#     _allowed_source = str(_allowed_raw).strip()
# ALLOWED_HOSTS = [h.strip() for h in _allowed_source.split(',') if h.strip()]
# # إنتاج DigitalOcean (يُضاف إذا لم يكن في المتغير)
# if 'radar-rbvob.ondigitalocean.app' not in ALLOWED_HOSTS:
#     ALLOWED_HOSTS.append('radar-rbvob.ondigitalocean.app')

ALLOWED_HOSTS=['radar-rbvob.ondigitalocean.app','*']

CSRF_TRUSTED_ORIGINS=['https://radar-rbvob.ondigitalocean.app']



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'users.apps.UsersConfig',
    'stores.apps.StoresConfig',
    'products.apps.ProductsConfig',
    'orders.apps.OrdersConfig',
]

# WhiteNoise للإنتاج فقط — في التطوير يعرض runserver الـ static من التطبيقات بدون تعارض
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
]
if not DEBUG:
    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')
MIDDLEWARE.extend(
    [
        'django.contrib.sessions.middleware.SessionMiddleware',
        'corsheaders.middleware.CorsMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ]
)

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# قاعدة البيانات: DJANGO_USE_SQLITE=1 يفرض SQLite محلياً حتى لو DATABASE_URL موجود في النظام
_db_url = (os.environ.get('DATABASE_URL') or '').strip()
_use_sqlite = _env_bool('DJANGO_USE_SQLITE', False)
if _db_url and not _use_sqlite:
    _ssl_require = _env_bool("DATABASE_SSL_REQUIRE", False)
    DATABASES = {
        'default': dj_database_url.parse(
            _db_url,
            conn_max_age=600,
            ssl_require=_ssl_require,
        ),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            # التطوير المحلي: افتراضياً استخدم قاعدة backend/db.sqlite3
            # يمكن فرض مسار مختلف عبر DJANGO_SQLITE_PATH عند الحاجة.
            'NAME': os.environ.get('DJANGO_SQLITE_PATH') or (BASE_DIR / 'db.sqlite3'),
        }
    }


AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
else:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'users.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'ROTATE_REFRESH_TOKENS': True,
}

# في التطوير: اسمح بأي أصل (localhost:3000 وغيره) حتى لا يعطل CORS_ALLOWED_ORIGINS من الإنتاج
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    _cors_raw = os.environ.get('CORS_ALLOWED_ORIGINS', '').strip()
    if _cors_raw:
        CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_raw.split(',') if o.strip()]
        CORS_ALLOW_ALL_ORIGINS = False
    else:
        CORS_ALLOW_ALL_ORIGINS = True

_RENDER = os.environ.get('RENDER', '').strip().lower() in ('1', 'true', 'yes')
if not DEBUG and _RENDER:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '').strip()
if _csrf_origins:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(',') if o.strip()]

ULTRAMSG_INSTANCE_ID = os.environ.get('ULTRAMSG_INSTANCE_ID', '')
ULTRAMSG_TOKEN = os.environ.get('ULTRAMSG_TOKEN', '')
WHATSAPP_DEBUG_MODE = _env_bool('WHATSAPP_DEBUG_MODE', True)
