"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# تحميل backend/.env للتطوير المحلي فقط.
# ملاحظة: داخل Docker Compose نريد أن تبقى متغيرات الـ environment (مثل DATABASE_URL)
# هي المسيطرة، لذلك لا نستخدم override=True هنا.
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / '.env', override=False)
except ImportError:
    pass

import dj_database_url


def _env_bool(name: str, default: bool = True) -> bool:
    """قيمة فارغة أو غير معرّفة = الافتراضي (يتفادى DEBUG='' → False)."""
    v = os.environ.get(name)
    if v is None:
        return default
    s = str(v).strip()
    if s == '':
        return default
    return s.lower() in ('1', 'true', 'yes', 'on')


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-7ulo5xvt3*-qiu3&_4@-u2#4avvx6n0yyv+ry4lbsf^)s31lcr',
)

DEBUG = _env_bool('DEBUG', True)

# محلي: localhost و127 وIPv6 (::1) وtestserver — يتفادى DisallowedHost مع البروكسي وVite على ويندوز
# إنتاج: عرّف ALLOWED_HOSTS في متغيرات البيئة على المنصة
_default_allowed = 'localhost,127.0.0.1,::1,testserver'
_allowed_raw = os.environ.get('ALLOWED_HOSTS')
if _allowed_raw is None or not str(_allowed_raw).strip():
    _allowed_source = _default_allowed
else:
    _allowed_source = str(_allowed_raw).strip()
ALLOWED_HOSTS = [h.strip() for h in _allowed_source.split(',') if h.strip()]
if 'radar-rbvob.ondigitalocean.app' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('radar-rbvob.ondigitalocean.app')
# مع DEBUG محلياً: أضف المضيفين المحليين حتى لو كان ALLOWED_HOSTS في .env للإنتاج فقط
if DEBUG:
    for _h in ('127.0.0.1', 'localhost', '::1', 'testserver'):
        if _h not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_h)


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'users.apps.UsersConfig',
    'stores.apps.StoresConfig',
    'products.apps.ProductsConfig',
    'orders.apps.OrdersConfig',
]

# DigitalOcean Spaces (S3-compatible)
_spaces_key = (os.environ.get('AWS_ACCESS_KEY_ID') or '').strip()
_spaces_secret = (os.environ.get('AWS_SECRET_ACCESS_KEY') or '').strip()
_spaces_bucket = (os.environ.get('AWS_STORAGE_BUCKET_NAME') or '').strip()
_spaces_config_ok = bool(_spaces_key and _spaces_secret and _spaces_bucket)
# إذا وُجدت كل مفاتيح Spaces ونقطة النهاية يُفعّل التخزين دائماً (لا يُعطّله USE_DO_SPACES)
_use_do_spaces = _spaces_config_ok
if _use_do_spaces:
    INSTALLED_APPS.insert(6, 'storages')

# WhiteNoise مباشرة بعد SecurityMiddleware حتى تُخدم ملفات admin/static في الإنتاج بشكل صحيح
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# قاعدة البيانات: DJANGO_USE_SQLITE=1 يفرض SQLite محلياً حتى لو DATABASE_URL موجود في النظام
_db_url = (os.environ.get('DATABASE_URL') or '').strip()
_use_sqlite = _env_bool('DJANGO_USE_SQLITE', False)
if _db_url and not _use_sqlite:
    _ssl_require = _env_bool("DATABASE_SSL_REQUIRE", False)
    DATABASES = {
        'default': dj_database_url.parse(
            _db_url,
            conn_max_age=600,
            ssl_require=_ssl_require,
        ),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            # التطوير المحلي: افتراضياً استخدم قاعدة backend/db.sqlite3
            # يمكن فرض مسار مختلف عبر DJANGO_SQLITE_PATH عند الحاجة.
            'NAME': os.environ.get('DJANGO_SQLITE_PATH') or (BASE_DIR / 'db.sqlite3'),
        }
    }


AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

_staticfiles_backend = (
    'django.contrib.staticfiles.storage.StaticFilesStorage'
    if DEBUG
    else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
)
STATICFILES_STORAGE = _staticfiles_backend

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

USE_DO_SPACES = _use_do_spaces

if _use_do_spaces:
    # مفاتيح Spaces (أنشئها من لوحة DO: API → Spaces Keys)
    AWS_ACCESS_KEY_ID = _spaces_key
    AWS_SECRET_ACCESS_KEY = _spaces_secret
    AWS_STORAGE_BUCKET_NAME = _spaces_bucket
    AWS_S3_REGION_NAME = 'fra1'
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_ADDRESSING_STYLE = 'virtual'
    # عنوان boto3 / botocore: الإقليم فقط — لا تضمّن اسم الـ bucket في الـ host (يُمرَّر عبر AWS_STORAGE_BUCKET_NAME).
    # شكل خاطئ يُسبب SSLError أو hostname مكرر: https://bucket.fra1.digitaloceanspaces.com
    AWS_S3_ENDPOINT_URL = f'https://{AWS_S3_REGION_NAME}.digitaloceanspaces.com'
    # صلاحيات القراءة العامة للملفات المرفوعة (Spaces / S3-compatible)
    AWS_DEFAULT_ACL = 'public-read'
    # روابط مباشرة للملفات (بدون ?X-Amz-...)
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_OBJECT_PARAMETERS = {'ACL': 'public-read'}

    def _host_from_url(value: str) -> str:
        u = value.strip().rstrip('/')
        for p in ('https://', 'http://'):
            if u.startswith(p):
                u = u[len(p) :]
        return u.split('/')[0] if u else ''

    def _dedupe_bucket_in_hostname(hostname: str, bucket: str) -> str:
        """يمنع تكرار اسم الـ bucket في النطاق (مثل radar-images.radar-images.fra1...)."""
        if not hostname or not bucket:
            return hostname
        h = hostname.strip().lower().rstrip('.')
        b = bucket.strip().lower() + '.'
        while h.startswith(b + b):
            h = h[len(b) :]
        return h

    # CDN: اسم النطاق فقط (بدون https://) — يُستخدم في django-storages لبناء روابط الملفات
    _cdn_env = (os.environ.get('AWS_S3_CUSTOM_DOMAIN') or os.environ.get('SPACES_CDN_DOMAIN') or '').strip()
    _media_url_env = (os.environ.get('MEDIA_URL') or '').strip()
    _custom_domain = _host_from_url(_cdn_env) if _cdn_env else ''
    if not _custom_domain and _media_url_env.startswith(('http://', 'https://')):
        _custom_domain = _host_from_url(_media_url_env)
    _custom_domain = _dedupe_bucket_in_hostname(_custom_domain, AWS_STORAGE_BUCKET_NAME)
    if _custom_domain:
        AWS_S3_CUSTOM_DOMAIN = _custom_domain

    if _media_url_env:
        MEDIA_URL = _media_url_env if _media_url_env.endswith('/') else _media_url_env + '/'
    elif _custom_domain:
        # نفس النطاق في django-storages لبناء file.url على الـ CDN
        MEDIA_URL = f'https://{_custom_domain}/'
    elif AWS_STORAGE_BUCKET_NAME and AWS_S3_REGION_NAME:
        MEDIA_URL = (
            f'https://{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_REGION_NAME}.digitaloceanspaces.com/'
        )

    STORAGES = {
        'default': {'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage'},
        'staticfiles': {'BACKEND': _staticfiles_backend},
    }
    # Django 4.2+ يفضّل STORAGES؛ هذا السطر يوضّح نفس الخلفية (الملفات الافتراضية = S3)
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

AUTH_USER_MODEL = 'users.CustomUser'

SITE_ID = 1

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# dj-rest-auth: JWT integration
REST_USE_JWT = True

# allauth / Google OAuth (SPA will send access_token to backend)
_google_client_id = (os.environ.get("GOOGLE_CLIENT_ID") or "").strip()
_google_client_secret = (os.environ.get("GOOGLE_CLIENT_SECRET") or "").strip()
if _google_client_id and _google_client_secret:
    SOCIALACCOUNT_PROVIDERS = {
        "google": {
            "APP": {
                "client_id": _google_client_id,
                "secret": _google_client_secret,
                "key": "",
            }
        }
    }

# keep account flows simple for API usage
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_EMAIL_REQUIRED = False

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'ROTATE_REFRESH_TOKENS': True,
}

# في التطوير: اسمح بأي أصل (localhost:3000 وغيره) حتى لا يعطل CORS_ALLOWED_ORIGINS من الإنتاج
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    _cors_raw = os.environ.get('CORS_ALLOWED_ORIGINS', '').strip()
    if _cors_raw:
        CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_raw.split(',') if o.strip()]
        CORS_ALLOW_ALL_ORIGINS = False
    else:
        CORS_ALLOW_ALL_ORIGINS = True

_RENDER = os.environ.get('RENDER', '').strip().lower() in ('1', 'true', 'yes')
if not DEBUG and _RENDER:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# DigitalOcean App Platform (وغيره) خلف بروكسي HTTPS: بدون هذا قد تفشل جلسة لوحة الأدمن وCSRF
# عرّف DJANGO_USE_TLS_PROXY=1 في متغيرات البيئة على السيرفر
if not DEBUG and _env_bool('DJANGO_USE_TLS_PROXY', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '').strip()
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(',') if o.strip()] if _csrf_origins else []
# إنتاج DO (عند عدم تعريف CSRF_TRUSTED_ORIGINS في البيئة)
if not DEBUG and 'https://radar-rbvob.ondigitalocean.app' not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append('https://radar-rbvob.ondigitalocean.app')
if DEBUG:
    for _o in (
        'http://127.0.0.1:3000',
        'http://localhost:3000',
        'http://127.0.0.1:5173',
        'http://localhost:5173',
    ):
        if _o not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_o)

ULTRAMSG_INSTANCE_ID = os.environ.get('ULTRAMSG_INSTANCE_ID', '')
ULTRAMSG_TOKEN = os.environ.get('ULTRAMSG_TOKEN', '')
WHATSAPP_DEBUG_MODE = _env_bool('WHATSAPP_DEBUG_MODE', True)

# Email (SMTP) — DigitalOcean env vars
# Required env vars (recommended):
#   EMAIL_HOST, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = (os.environ.get('EMAIL_HOST') or '').strip()
EMAIL_HOST_USER = (os.environ.get('EMAIL_HOST_USER') or '').strip()
EMAIL_HOST_PASSWORD = (os.environ.get('EMAIL_HOST_PASSWORD') or '').strip()
EMAIL_USE_TLS = True
EMAIL_PORT = 587

# Optional, but nice to set
DEFAULT_FROM_EMAIL = (os.environ.get('DEFAULT_FROM_EMAIL') or EMAIL_HOST_USER or 'no-reply@radar.local').strip()
SERVER_EMAIL = (os.environ.get('SERVER_EMAIL') or DEFAULT_FROM_EMAIL).strip()
EMAIL_TIMEOUT = int((os.environ.get('EMAIL_TIMEOUT') or '20').strip() or 20)
