from django.urls import path
from .views import (
    AdminCommunityPointListCreateView,
    AdminCommunityPointDetailView,
    AdminCommunityPointModerateView,
    CategoryListView,
    CommunityCategoryListView,
    CommunityPointListView,
    CommunityPointMyListView,
    CommunityPointSubmitView,
    ServiceListView,
    NearbyStoreListView,
    StoreDetailView,
    ShopperStoreRatingView,
    MerchantStoreProfileView,
    PrimaryAdminStoreListView,
    PrimaryAdminStoreSuspendView,
    PrimaryAdminStoreCategoriesView,
    PrimaryAdminStoreCategoryDeleteView,
    PrimaryAdminCommunityCategoriesView,
    PrimaryAdminCommunityCategoryDeleteView,
)

urlpatterns = [
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('services/', ServiceListView.as_view(), name='service_list'),
    path('community/categories/', CommunityCategoryListView.as_view(), name='community_category_list'),
    path('community/points/', CommunityPointListView.as_view(), name='community_point_list'),
    path('community/points/mine/', CommunityPointMyListView.as_view(), name='community_point_mine'),
    path('community/points/submit/', CommunityPointSubmitView.as_view(), name='community_point_submit'),
    path('admin/community-points/', AdminCommunityPointListCreateView.as_view(), name='admin_community_point_list_create'),
    path('admin/community-points/<int:pk>/', AdminCommunityPointDetailView.as_view(), name='admin_community_point_detail'),
    path('admin/community-points/<int:pk>/moderate/', AdminCommunityPointModerateView.as_view(), name='admin_community_point_moderate'),
    path('stores/', NearbyStoreListView.as_view(), name='store_list'),
    path('stores/<int:pk>/', StoreDetailView.as_view(), name='store_detail'),
    path('stores/<int:pk>/rate/', ShopperStoreRatingView.as_view(), name='store_rate'),
    path('merchant/profile/', MerchantStoreProfileView.as_view(), name='merchant_store_profile'),
    path('admin/stores/', PrimaryAdminStoreListView.as_view(), name='primary_admin_store_list'),
    path('admin/stores/<int:pk>/suspend/', PrimaryAdminStoreSuspendView.as_view(), name='primary_admin_store_suspend'),
    path('admin/categories/', PrimaryAdminStoreCategoriesView.as_view(), name='primary_admin_store_categories'),
    path('admin/categories/<int:pk>/', PrimaryAdminStoreCategoryDeleteView.as_view(), name='primary_admin_store_category_delete'),
    path('admin/community/categories/', PrimaryAdminCommunityCategoriesView.as_view(), name='primary_admin_community_categories'),
    path('admin/community/categories/<int:pk>/', PrimaryAdminCommunityCategoryDeleteView.as_view(), name='primary_admin_community_category_delete'),
]
