# Generated by Django 6.0.3 on 2026-03-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/', verbose_name='لوغو المتجر'),
        ),
    ]
