# Generated by Django 6.0.3 on 2026-04-03 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_community_categories(apps, schema_editor):
    CommunityServiceCategory = apps.get_model('stores', 'CommunityServiceCategory')
    rows = [
        (
            1,
            'medical',
            'نقاط طبية',
            'مستشفيات حكومية، نقاط ميدانية، عيادات، ومراكز صحية وغيرها.',
        ),
        (
            2,
            'education',
            'نقاط تعليمية',
            'مدارس، نقاط تعليمية في مخيمات، دورات، وأي نشاط تعليمي مجتمعي.',
        ),
        (3, 'food', 'نقاط توزيع طعام (تكيات)', 'تكيات، صناديق خيرية لتوزيع الطعام، موائد، إلخ.'),
        (
            4,
            'water',
            'نقاط توزيع مياه',
            'حدد عند الإضافة: هل المياه صالحة للشرب أم لا.',
        ),
        (
            5,
            'institution',
            'مؤسسات مجتمعية',
            'محلية أو عالمية أو خيرية — اذكر في الوصف التفصيلي عمل المؤسسة بوضوح.',
        ),
    ]
    for sort_order, slug, name, hint in rows:
        CommunityServiceCategory.objects.update_or_create(
            slug=slug,
            defaults={
                'name': name,
                'description_hint': hint,
                'sort_order': sort_order,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_storerating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القسم')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='المعرّف')),
                ('description_hint', models.TextField(blank=True, help_text='يُعرض عند اقتراح نقطة في هذا القسم.', verbose_name='تلميح للمستخدم')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'قسم خدمة مجتمعية',
                'verbose_name_plural': 'أقسام الخدمات المجتمعية',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommunityServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='العنوان / اسم النقطة')),
                ('detail_description', models.TextField(verbose_name='وصف تفصيلي للخدمة')),
                ('latitude', models.FloatField(verbose_name='خط العرض')),
                ('longitude', models.FloatField(verbose_name='خط الطول')),
                ('address_text', models.TextField(verbose_name='الموقع النصي التفصيلي')),
                ('water_is_potable', models.BooleanField(blank=True, help_text='لقسم نقاط توزيع المياه فقط: هل المياه صالحة للشرب؟', null=True, verbose_name='مياه صالحة للشرب')),
                ('institution_scope', models.CharField(blank=True, choices=[('', '—'), ('local', 'محلية'), ('international', 'عالمية'), ('charity', 'خيرية')], help_text='لمؤسسات مجتمعية: محلية / عالمية / خيرية.', max_length=20, verbose_name='نطاق المؤسسة')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points', to='stores.communityservicecategory', verbose_name='القسم')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_points_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='راجعه')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_point_submissions', to=settings.AUTH_USER_MODEL, verbose_name='مقدّم الطلب')),
            ],
            options={
                'verbose_name': 'نقطة خدمة مجتمعية',
                'verbose_name_plural': 'نقاط الخدمات المجتمعية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_community_categories, migrations.RunPython.noop),
    ]
