# Generated by Django 6.0.3 on 2026-04-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_community_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='business_hours_note',
            field=models.TextField(blank=True, default='', verbose_name='مواعيد العمل (نص يظهر للمتسوّقين)'),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='business_hours_weekly',
            field=models.JSONField(blank=True, default=dict, help_text='مثال: {"0":[{"start":"09:00","end":"17:00"}],"1":[]}', verbose_name='جدول أسبوعي للحساب (أحد=0 … سبت=6)'),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='contact_whatsapp',
            field=models.CharField(blank=True, default='', help_text='أرقام مع رمز الدولة بدون + (مثال: 970599123456) لزر التواصل.', max_length=24, verbose_name='رقم واتساب للتواصل'),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='store_features',
            field=models.JSONField(blank=True, default=list, verbose_name='مميزات المتجر (حتى 10)'),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='store_timezone',
            field=models.CharField(blank=True, default='Asia/Gaza', max_length=64, verbose_name='المنطقة الزمنية'),
        ),
    ]
