# Generated by Django 6.0 on 2026-04-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_community_point_hide_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityservicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_categories/', verbose_name='صورة القسم'),
        ),
    ]
