# Generated by Django 6.0.4 on 2026-04-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_communityservicecategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='يمكن اختيار أكثر من قسم للمتجر لظهوره ضمن أكثر من فلتر.', related_name='stores_multi', to='stores.category', verbose_name='أقسام المتجر (متعدد)'),
        ),
    ]
