# Generated by Django 6.0.3 on 2026-03-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'المفضلة',
                'verbose_name_plural': 'المفضلات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المنتج')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة المنتج')),
                ('is_archived', models.BooleanField(default=False, verbose_name='مؤرشف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SponsoredAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإعلان')),
                ('description', models.TextField(verbose_name='تفاصيل الإعلان')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='صورة الإعلان')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('active', 'نشط'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الإعلان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
