# Generated by Django 6.0.3 on 2026-03-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_subscriptionrenewalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoredad',
            name='payment_receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='ad_receipts/', verbose_name='إشعار دفع الإعلان'),
        ),
    ]
