# Generated by Django 6.0.3 on 2026-04-03 14:10

from django.db import migrations, models


def backfill_approved_at(apps, schema_editor):
    SponsoredAd = apps.get_model('products', 'SponsoredAd')
    for ad in SponsoredAd.objects.filter(status='active', approved_at__isnull=True):
        ad.approved_at = ad.created_at
        ad.save(update_fields=['approved_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_storefavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoredad',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الموافقة (بداية الظهور 24 ساعة)'),
        ),
        migrations.RunPython(backfill_approved_at, migrations.RunPython.noop),
    ]
