# Generated by Django 6.0.3 on 2026-04-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_favorite_sponsored_ad_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoredad',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='تفاصيل الإعلان'),
        ),
        migrations.AlterField(
            model_name='sponsoredad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='صورة الإعلان'),
        ),
    ]
