# Generated by Django 6.0.3 on 2026-04-03 15:24

import os

import django.db.models.deletion
from django.core.files.base import ContentFile
from django.db import migrations, models


def copy_legacy_product_and_ad_images(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductGalleryImage = apps.get_model('products', 'ProductGalleryImage')
    SponsoredAd = apps.get_model('products', 'SponsoredAd')
    SponsoredAdGalleryImage = apps.get_model('products', 'SponsoredAdGalleryImage')

    for p in Product.objects.exclude(image='').exclude(image__isnull=True):
        try:
            with p.image.open('rb') as f:
                data = f.read()
            gi = ProductGalleryImage(product_id=p.pk, sort_order=0)
            gi.image.save(os.path.basename(p.image.name), ContentFile(data), save=True)
        except Exception:
            continue

    for ad in SponsoredAd.objects.exclude(image='').exclude(image__isnull=True):
        try:
            with ad.image.open('rb') as f:
                data = f.read()
            gi = SponsoredAdGalleryImage(sponsored_ad_id=ad.pk, sort_order=0)
            gi.image.save(os.path.basename(ad.image.name), ContentFile(data), save=True)
        except Exception:
            continue


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_sponsored_ad_optional_image_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SponsoredAdGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/gallery/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('sponsored_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.sponsoredad')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(copy_legacy_product_and_ad_images, noop_reverse),
    ]
