# Generated by Django 6.0.4 on 2026-04-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_product_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoredad',
            name='payment_method',
            field=models.CharField(choices=[('balipay_wallet', 'محفظة بال باي'), ('bank_palestine', 'بنك فلسطين'), ('other', 'أخرى')], default='balipay_wallet', max_length=20, verbose_name='قناة الدفع'),
        ),
    ]
