# Generated by Django 6.0 on 2026-04-09 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_sponsored_ad_payment_other'),
        ('stores', '0011_community_point_hide_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrenewalrequest',
            name='amount_ils',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='اختياري: تُستخدم لحساب أرباح المشروع.', max_digits=10, null=True, verbose_name='قيمة التحويل (شيكل)'),
        ),
        migrations.AddField(
            model_name='subscriptionrenewalrequest',
            name='payment_method',
            field=models.CharField(choices=[('balipay_wallet', 'محفظة بال باي'), ('bank_palestine', 'بنك فلسطين'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='قناة الدفع'),
        ),
        migrations.CreateModel(
            name='FinanceTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sponsored_ad', 'إعلان ممول'), ('subscription_renewal', 'تجديد اشتراك')], db_index=True, max_length=30, verbose_name='نوع التحويل')),
                ('payment_method', models.CharField(choices=[('balipay_wallet', 'محفظة بال باي'), ('bank_palestine', 'بنك فلسطين'), ('other', 'أخرى')], db_index=True, default='other', max_length=20, verbose_name='قناة الدفع')),
                ('amount_ils', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ (شيكل)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sponsored_ad', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_transfer', to='products.sponsoredad')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_transfers', to='stores.storeprofile')),
                ('subscription_renewal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_transfer', to='products.subscriptionrenewalrequest')),
            ],
            options={
                'verbose_name': 'تحويل مالي',
                'verbose_name_plural': 'تحويلات مالية',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
