# Generated by Django 6.0 on 2026-04-13 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_subscriptionrenewalrequest_amount_ils_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAppPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='العنوان')),
                ('amount_ils', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ (شيكل)')),
                ('status', models.CharField(choices=[('paid', 'مدفوع'), ('planned', 'قيد الدفع')], db_index=True, default='paid', max_length=20, verbose_name='الحالة')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_app_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دفعة للتطبيق',
                'verbose_name_plural': 'مدفوعات للتطبيق',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
